### ISSUE TITLE
Parameters stride_length and window_size

### ISSUE THREAD

**Issue by leptonleo** [mohit1997/RPPG_2SR#1]
May I know more about the parameters "stride_length" and "window_size"? What are they? and how to set these parameters? Can give some examples about that? Thank you very much.

**Comment by mohit1997** [comment]
Please take a look at this paper - "A Novel Algorithm for Remote Photoplethysmography: Spatial Subspace Rotation". This project was just an implementation, and therefore there are no new variables introduced by us. If you still have issues please let me know.
